JV 2021: Redaktionelle Anpassungen
Schachjugend/Spielordnung pull request #77
Opened 2021-06-03 06:47 UTC by tgoettel9401

Begründung:

Mehrere deutsche EInzelmeisterschaften zur gleichen Zeit (2.1 AB, 2.8)
Die Regelung sollte sich in der Ordnung und nicht in den AB befinden. Wie die DEM und die DVM 2020 gezeigt haben, kann es zudem dazu kommen, dass unterschiedliche Altersklassen einer DEM bzw. DVM zu verschiedenen Zeiten ausgetragen werden. Auch in diesem Fall soll ein Spieler nur für eines der Turniere startberechtigt sein.

Bedenkzeiten: Die Bedenkzeiten sollten sich, wie in 2.5, in der Ordnung und nicht in den Ausführungsbestimmungen befinden.

DLM 2020: Der 2019 angenommene Antrag sah nicht vor, die die DLM 2020 betreffenden Regelungen zu gegebenem Zeitpunkt wieder zu entfernen.

Korrektur von Verweisen: Der 2020 angenommene Antrag zur DVM sah nicht vor, entsprechend notwendige Anpassungen von Verweisen vorzunehmen. Dies wird hiermit nachgeholt. Gleichzeitig wird die Lesbarkeit von Ziffer 3.3 verbessert.

Gedrucktes Vorhalten der Ausführungsbestimmungen: Das gedruckte Vorhalten der Spielordnung samt Ausführungsbestimmungen ist heutzutage nicht mehr notwendig.

2021-06-03 09:22 UTC, hkoppen requested changes
Du hast 7.1 AB gestrichen, was nicht der Fall sein sollte.

2021-06-03 14:02 UTC, tgoettel9401 commented
> Du hast 7.1 AB gestrichen, was nicht der Fall sein sollte.

Danke, da hab ich übersehen, dass ein Absatz aus 7.1 AB drin bleiben sollte. Ist jetzt angepasst.

2021-06-04 22:11 UTC, hkoppen approved these changes

2021-07-04 13:28 UTC, KWodzinski commented
Hier scheint es 2 Konflikte zu geben. 
Die neue Fassung von 6.5 sollte sein "Kaderspieler des Deutschen Schachbundes erhalten in ihrer jeweiligen Altersklasse einen Startplatz."
Und in den AB zu 6.5. scheint die U8 zu fehlen. DBSB ist in der neuen Version auch nicht mehr abgekürzt.

2021-07-06 09:21 UTC, merged