Änderungen Ziffer 17 durch AK Schulschach
Schachjugend/Spielordnung pull request #90
Opened 2024-11-17 16:06 UTC by hkoppen

Siehe Mail

2024-11-18 15:22 UTC, betterclaimesc approved these changes

2024-11-18 15:33 UTC, swewagner requested changes

2024-11-18 15:33 UTC, swewagner commented on Spielordnung.md
> +    > Der AK Schulschach gibt die Teilnehmerzahl der einzelnen WKs bis 31. Dezember bekannt.
bis *zum* 31. Dezember (des Vorjahres? zwei Jahre vorher?)

2024-11-19 17:19 UTC, hkoppen commented on Spielordnung.md
> +    > Der AK Schulschach gibt die Teilnehmerzahl der einzelnen WKs bis 31. Dezember bekannt.
Angepasst

2024-11-19 17:29 UTC, paulusjeffrey approved these changes

2024-11-19 17:39 UTC, swewagner approved these changes

2024-11-19 17:40 UTC, merged